language: python

python:
  - 3.6

before_install:
  - sudo apt-get install python-pip
  
install:  
  - pip install sphinx
  - pip install sphinx_rtd_theme

script:
  - touch .nojekyll # Ignore using Jekyll theme from GitHub pages and use our build
  - sphinx-build -b html docs/howtosetup/source/ docs/howtosetup/build/
  - cd docs/howtosetup
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ./docs/howtosetup/build/html/
  on:
    branch: master
